
GET http://127.0.0.1:5001/korazon-dc77a/us-central1/api


###
POST http://127.0.0.1:5001/korazon-dc77a/us-central1/api
Content-Type: application/json

{
  "name": "Korazon",
  "age": "30"
}

###
DELETE http://127.0.0.1:5001/korazon-dc77a/us-central1/api

###
PUT http://127.0.0.1:5001/korazon-dc77a/us-central1/api
