// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCD6POJAG4zMcxWK83vw1hRK94hm46cIxQ',
    appId: '1:368181595286:web:160fffede7a286998046b7',
    messagingSenderId: '368181595286',
    projectId: 'korazon-dc77a',
    authDomain: 'korazon-dc77a.firebaseapp.com',
    storageBucket: 'korazon-dc77a.appspot.com',
    measurementId: 'G-CXHZTWF7T8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_dXh82cbWrSjAXqR_7Dxf03HRArMhols',
    appId: '1:368181595286:android:3b7d7e98605602f08046b7',
    messagingSenderId: '368181595286',
    projectId: 'korazon-dc77a',
    storageBucket: 'korazon-dc77a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASmVtEzDVL1OHtdyLIW26UbXfoyGtZVV0',
    appId: '1:368181595286:ios:17663aee32b079818046b7',
    messagingSenderId: '368181595286',
    projectId: 'korazon-dc77a',
    storageBucket: 'korazon-dc77a.appspot.com',
    iosBundleId: 'com.example.korazon',
  );

}